service: contentful-extensions-bucket
frameworkVersion: ">=1.38.0 <2.0.0"

provider:
  name: aws
  region: eu-west-1
  stage: prod
  environment:
    EXTENSIONS_BUCKET_NAME: xebiafr-${self:custom.stage}-contentful-extensions-bucket

custom:
  stage: ${opt:stage, self:provider.stage}

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.EXTENSIONS_BUCKET_NAME}
        AccessControl: PublicRead
